import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Button from '../components/ui/button';
import { signIn, signOut, useSession } from 'next-auth/react';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>To-Doo App</title>
        <meta name="description" content="Generated by lorre huggan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center justify-center">
        <Auth />
      </main>
    </>
  );
};

export default Home;

const Auth: React.FC = () => {
  return (
    <Button
      {...{
        theme: 'tertiary',
        size: 'large',
        onClick: () => signIn(),
        title: 'Sign in',
      }}
    />
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  /* Checking if the user has a session token. If they do, it redirects them to the dashboard. */
  const { cookies } = ctx.req;
  const session = cookies['next-auth.session-token'];

  if (session) {
    return {
      redirect: {
        destination: '/dashboard',
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};
